//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET.WebForm.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.WSBeginnersSoap")]
    public interface WSBeginnersSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ASP.NET.WebForm.WS.HelloWorldResponse HelloWorld(ASP.NET.WebForm.WS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ASP.NET.WebForm.WS.HelloWorldResponse> HelloWorldAsync(ASP.NET.WebForm.WS.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name items from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Food", ReplyAction="*")]
        ASP.NET.WebForm.WS.FoodResponse Food(ASP.NET.WebForm.WS.FoodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Food", ReplyAction="*")]
        System.Threading.Tasks.Task<ASP.NET.WebForm.WS.FoodResponse> FoodAsync(ASP.NET.WebForm.WS.FoodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        double Suma(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumaAsync(double n1, double n2);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ASP.NET.WebForm.WS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ASP.NET.WebForm.WS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASP.NET.WebForm.WS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ASP.NET.WebForm.WS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FoodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Food", Namespace="http://tempuri.org/", Order=0)]
        public ASP.NET.WebForm.WS.FoodRequestBody Body;
        
        public FoodRequest() {
        }
        
        public FoodRequest(ASP.NET.WebForm.WS.FoodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FoodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string items;
        
        public FoodRequestBody() {
        }
        
        public FoodRequestBody(string items) {
            this.items = items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FoodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FoodResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASP.NET.WebForm.WS.FoodResponseBody Body;
        
        public FoodResponse() {
        }
        
        public FoodResponse(ASP.NET.WebForm.WS.FoodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FoodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FoodResult;
        
        public FoodResponseBody() {
        }
        
        public FoodResponseBody(string FoodResult) {
            this.FoodResult = FoodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSBeginnersSoapChannel : ASP.NET.WebForm.WS.WSBeginnersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSBeginnersSoapClient : System.ServiceModel.ClientBase<ASP.NET.WebForm.WS.WSBeginnersSoap>, ASP.NET.WebForm.WS.WSBeginnersSoap {
        
        public WSBeginnersSoapClient() {
        }
        
        public WSBeginnersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSBeginnersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBeginnersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBeginnersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP.NET.WebForm.WS.HelloWorldResponse ASP.NET.WebForm.WS.WSBeginnersSoap.HelloWorld(ASP.NET.WebForm.WS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ASP.NET.WebForm.WS.HelloWorldRequest inValue = new ASP.NET.WebForm.WS.HelloWorldRequest();
            inValue.Body = new ASP.NET.WebForm.WS.HelloWorldRequestBody();
            ASP.NET.WebForm.WS.HelloWorldResponse retVal = ((ASP.NET.WebForm.WS.WSBeginnersSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP.NET.WebForm.WS.HelloWorldResponse> ASP.NET.WebForm.WS.WSBeginnersSoap.HelloWorldAsync(ASP.NET.WebForm.WS.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP.NET.WebForm.WS.HelloWorldResponse> HelloWorldAsync() {
            ASP.NET.WebForm.WS.HelloWorldRequest inValue = new ASP.NET.WebForm.WS.HelloWorldRequest();
            inValue.Body = new ASP.NET.WebForm.WS.HelloWorldRequestBody();
            return ((ASP.NET.WebForm.WS.WSBeginnersSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASP.NET.WebForm.WS.FoodResponse ASP.NET.WebForm.WS.WSBeginnersSoap.Food(ASP.NET.WebForm.WS.FoodRequest request) {
            return base.Channel.Food(request);
        }
        
        public string Food(string items) {
            ASP.NET.WebForm.WS.FoodRequest inValue = new ASP.NET.WebForm.WS.FoodRequest();
            inValue.Body = new ASP.NET.WebForm.WS.FoodRequestBody();
            inValue.Body.items = items;
            ASP.NET.WebForm.WS.FoodResponse retVal = ((ASP.NET.WebForm.WS.WSBeginnersSoap)(this)).Food(inValue);
            return retVal.Body.FoodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASP.NET.WebForm.WS.FoodResponse> ASP.NET.WebForm.WS.WSBeginnersSoap.FoodAsync(ASP.NET.WebForm.WS.FoodRequest request) {
            return base.Channel.FoodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASP.NET.WebForm.WS.FoodResponse> FoodAsync(string items) {
            ASP.NET.WebForm.WS.FoodRequest inValue = new ASP.NET.WebForm.WS.FoodRequest();
            inValue.Body = new ASP.NET.WebForm.WS.FoodRequestBody();
            inValue.Body.items = items;
            return ((ASP.NET.WebForm.WS.WSBeginnersSoap)(this)).FoodAsync(inValue);
        }
        
        public double Suma(double n1, double n2) {
            return base.Channel.Suma(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> SumaAsync(double n1, double n2) {
            return base.Channel.SumaAsync(n1, n2);
        }
    }
}
